services:
  # üêò PostgreSQL (O Banco de Dados)
  postgres:
    image: postgres:16-alpine
    container_name: flashsale-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flashsale_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flashsale-net

  # ‚ö° Redis (O Cache/Estoque R√°pido)
  redis:
    image: redis:alpine
    container_name: flashsale-redis
    ports:
      - "6379:6379"
    networks:
      - flashsale-net

  # ü¶ì Zookeeper (O Gerente do Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    container_name: flashsale-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - flashsale-net

  # üì® Kafka (O Carteiro)
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: flashsale-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Configura√ß√£o m√°gica para funcionar dentro do Docker e na sua m√°quina (localhost):
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - flashsale-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: flashsale-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - flashsale-net

volumes:
  postgres_data:

networks:
  flashsale-net:
    driver: bridge