server:
  port: 8080

spring:
  application:
    name: flashsale-engine

  # üêò CONFIGURA√á√ÉO DO POSTGRES
  datasource:
    url: jdbc:postgresql://localhost:5432/flashsale_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # ‚öôÔ∏è CONFIGURA√á√ÉO DO JPA / HIBERNATE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ‚ö° CONFIGURA√á√ÉO DO REDIS
  data:
    redis:
      host: localhost
      port: 6379

  # üì® CONFIGURA√á√ÉO DO KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flashsale-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer